---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.80.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2022.1.2
- name: goreleaser/goreleaser@v1.12.3
- name: securego/gosec@v2.14.0
- name: reviewdog/reviewdog@v0.14.1
- name: mvdan/sh@v3.5.1
- name: koalaman/shellcheck@v0.8.0
- name: rhysd/actionlint@v1.6.21
- name: rust-lang/mdBook@v0.4.21
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.32.1
