---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.30.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2023.1.3
- name: goreleaser/goreleaser@v1.19.2
- name: securego/gosec@v2.16.0
- name: reviewdog/reviewdog@v0.14.2
- name: mvdan/sh@v3.7.0
- name: koalaman/shellcheck@v0.9.0
- name: rhysd/actionlint@v1.6.25
- name: rust-lang/mdBook@v0.4.32
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.43.1
