---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.123.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2022.1.2
- name: goreleaser/goreleaser@v1.14.1
- name: securego/gosec@v2.14.0
- name: reviewdog/reviewdog@v0.14.1
- name: mvdan/sh@v3.6.0
- name: koalaman/shellcheck@v0.9.0
- name: rhysd/actionlint@v1.6.23
- name: rust-lang/mdBook@v0.4.25
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.36.1
